apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2024-10-15T173753Z
  name: policy-exc-req-c8764j5022c-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: restrict-automount-sa-token
    ruleNames:
    - autogen-validate-automountServiceAccountToken
    - validate-automountServiceAccountToken
  match:
    any:
    - resources:
        kinds:
        - Deployment
        names:
        - argocd-dex-server
        - argocd-notifications-controller
        - argocd-server
        - argocd-applicationset-controller
        - argocd-repo-server
        - argocd-redis
        namespaces:
        - argocd
    - resources:
        kinds:
        - ReplicaSet
        names:
        - argocd-notifications-controller-6847bd5c98
        - argocd-repo-server-7fcf5f5654
        - argocd-redis-f9db77795
        - argocd-applicationset-controller-587b5c864b
        - argocd-server-59775fbfb5
        - argocd-dex-server-6d64fcc4fc
        namespaces:
        - argocd
    - resources:
        kinds:
        - StatefulSet
        names:
        - argocd-application-controller
        namespaces:
        - argocd
    - resources:
        kinds:
        - Pod
        names:
        - argocd-repo-server-7fcf5f5654-8pcbq
        - argocd-redis-f9db77795-6bktr
        - argocd-notifications-controller-6847bd5c98-2bvdp
        - argocd-application-controller-0
        - argocd-dex-server-6d64fcc4fc-k695h
        - argocd-applicationset-controller-587b5c864b-7bvwb
        - argocd-server-59775fbfb5-q5qd8
        namespaces:
        - argocd
