apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2024-10-15T153036Z
  name: policy-exc-req-j6681y7772e-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: restrict-automount-sa-token
    ruleNames:
    - validate-automountServiceAccountToken
    - autogen-validate-automountServiceAccountToken
  match:
    any:
    - resources:
        kinds:
        - Deployment
        names:
        - coredns
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Pod
        names:
        - coredns-76f75df574-2g8jd
        - kindnet-r85tt
        - etcd-rbac-control-plane
        - kube-scheduler-rbac-control-plane
        - coredns-76f75df574-ln6rf
        - kube-proxy-59thp
        - kube-apiserver-rbac-control-plane
        - kube-controller-manager-rbac-control-plane
        namespaces:
        - kube-system
    - resources:
        kinds:
        - ReplicaSet
        names:
        - coredns-76f75df574
        namespaces:
        - kube-system
    - resources:
        kinds:
        - DaemonSet
        names:
        - kindnet
        - kube-proxy
        namespaces:
        - kube-system
