apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2024-09-23T105213Z
  name: policy-exc-req-c3837i7240j-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: restrict-wildcard-resources
    ruleNames:
    - wildcard-resources
    - autogen-wildcard-resources
  match:
    any:
    - resources:
        kinds:
        - Role
        names:
        - kyverno:admission-controller
        - kyverno:cleanup-controller
        - kyverno:reports-controller
        - kyverno:background-controller
        - kyverno-installer
        namespaces:
        - kyverno
