apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2024-10-16T134254Z
  name: policy-exc-req-r2574j1551u-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: restrict-automount-sa-token
    ruleNames:
    - autogen-validate-automountServiceAccountToken
    - validate-automountServiceAccountToken
  match:
    any:
    - resources:
        kinds:
        - Deployment
        names:
        - httpd
        namespaces:
        - httpd
    - resources:
        kinds:
        - ReplicaSet
        names:
        - httpd-5c98f79dfc
        namespaces:
        - httpd
    - resources:
        kinds:
        - Pod
        names:
        - httpd-5c98f79dfc-88r8v
        - httpd-5c98f79dfc-fgr4c
        - httpd-5c98f79dfc-9kbmf
        namespaces:
        - httpd
